name: polarstar_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.16+39
# version: 1.0.0+24

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.3
  
  provider: ^5.0.0

  crypto: ^3.0.1 

  get:

  get_storage:

  image_picker: ^0.8.2
  
  json_annotation: ^4.0.1

  # firebase_core: ^1.1.0
  
  # firebase_messaging: ^10.0.4

  # firebase_analytics: ^8.2.0

  cached_network_image: ^3.1.0

  path_provider: ^2.0.2

  sqflite: ^2.0.0+4

  wechat_assets_picker : ^6.0.4

  string_validator: ^0.3.0

  swipedetector: ^1.2.0

  sqflite_migration: ^0.3.0

  web_socket_channel: ^2.1.0

  flutter_keyboard_visibility: ^5.1.1

  file_picker: ^4.3.2

  dio: ^4.0.4

  platform: ^3.1.0

  linkwell: ^2.0.6

  # kakao_flutter_sdk: ^1.1.0 

  # kakao_flutter_sdk_user: ^1.1.0

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  socket_io_client: ^1.0.2
  webview_flutter: ^3.0.0

  permission_handler: ^8.3.0

  flutter_downloader: ^1.7.2
  device_info_plus: ^3.2.1
  image_size_getter: ^1.0.0
  package_info: ^2.0.2
  flutter_image_compress: ^1.1.0
  video_thumbnail: ^0.4.3
  video_player: ^2.2.18
  store_redirect: ^2.0.1

  # push notification
  pushy_flutter: ^2.0.4
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.20
  launch_review: ^3.0.1

  # firebase_analytics: ^9.1.1
  # firebase_core: ^1.15.0
  flurry: ^1.0.0

  
dependency_overrides:
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/897.png
    - assets/images/898.png
    - assets/images/894.png
    - assets/images/568.png
    - assets/images/891.png
    - assets/images/591.png
    - assets/images/589.png
    - assets/images/64.png
    - assets/images/594.png
    - assets/images/940.png
    - assets/images/654.png
    - assets/images/15_4.png
    - assets/images/spinner.gif
    - assets/images/938.png
    - assets/images/982.png
    - assets/images/eye_off_fill.png
    - assets/images/978.png
    - assets/images/star.png
    - assets/images/good.png
    - assets/images/comment.png
    - assets/images/968.png
    - assets/images/970.png
    - assets/images/627.png
    - assets/images/848.png
    - assets/images/invalid_name.png
    - assets/images/849.png
    - assets/images/like_red.png
    - assets/images/scrap_none.png
    - assets/images/temp_pencil.png
    - assets/images/camera.png
    - assets/images/415.png
    - assets/images/414.png
    - assets/images/413.png
    - assets/images/class_1.png
    - assets/images/class_2.png
    - assets/images/class_3.png
    - assets/images/class_4.png
    - assets/images/class_5.png
    - assets/images/class_6.png
    - assets/images/class_7.png
    - assets/images/class_8.png
    - assets/images/class_9.png
    - assets/images/class_10.png
    # 일단 이까지만 지움
    - assets/images/board_bell.png
    - assets/images/icn_comment_normal.png
    - assets/images/icn_like_normal.png
    - assets/images/icn_like_selected.png
    - assets/images/icn_star_normal.png
    - assets/images/icn_star_selected.png

    - assets/images/icn_more.png
    - assets/images/icn_reply_like_color.png
    - assets/images/icn_reply_like_selected.png
    - assets/images/icn_reply_star_selected.png
    - assets/images/icn_reply_comment_normal.png
    - assets/images/icn_reply_star_normal.png

    - assets/images/icn_home_normal.png
    - assets/images/icn_home_selected.png
    - assets/images/icn_calendar_normal.png
    - assets/images/icn_calendar_selected.png
    - assets/images/icn_check_normal.png
    - assets/images/icn_check_selected.png
    - assets/images/icn_alarm_normal.png
    - assets/images/icn_alarm_selected.png
    - assets/images/icn_profile_normal.png
    - assets/images/icn_profile_selected.png

    - assets/images/icn_send_white.png
    - assets/images/icn_detail.png
    - assets/images/back_icon.png
    - assets/images/img_main_illust.png
    - assets/images/icn_search.png

    - assets/images/icn_setting.png
    - assets/images/segmentation_1.png
    - assets/images/icn_plus.png
    - assets/images/menu.png
    - assets/images/icn_pen.png
    - assets/images/icn_book.png
    - assets/images/bookmark_followed.png
    - assets/images/bookmark_none.png

    # login
    - assets/images/polarstar_logo.png

    # Main Page Scroll
    - assets/images/378.png
    - assets/images/panda.png
    - assets/images/banner_panda_event.png
    - assets/images/banner_panda_hello.png

    # Outside Preview
    - assets/images/371.png

    # ClassView
    - assets/images/icn_back_white.png
    - assets/images/icn_star_normal_white.png
    - assets/images/icn_star_selected_fill.png
    - assets/images/174.png
    - assets/images/drop_down_arrow.png
    - assets/images/186.png
    - assets/images/like_class.png

    # Class Star
    - assets/images/star_0.png
    - assets/images/star_10.png
    - assets/images/star_20.png
    - assets/images/star_30.png
    - assets/images/star_40.png
    - assets/images/star_50.png
    - assets/images/star_60.png
    - assets/images/star_70.png
    - assets/images/star_80.png
    - assets/images/star_90.png
    - assets/images/star_100.png


    # Timetable
    - assets/images/timetable_edit_name.png
    - assets/images/timetable_visible_range.png
    - assets/images/timetable_save_picture.png
    - assets/images/timetable_share_links.png
    - assets/images/timetable_delete.png
    - assets/images/timetable_set_default.png
    - assets/images/community_create.png
    - assets/images/timetable_addclass_close.png
    - assets/images/timetable_filter_delete.png
    - assets/images/class_chat_profile.png
    - assets/images/right_arrow.png

    - assets/images/timetable_direct_book.png
    - assets/images/timetable_direct_professr.png
    - assets/images/timetable_direct_clock.png
    - assets/images/timetable_direct_location.png
    - assets/images/timetable_direct_delete.png


    # Community
    - assets/images/comment_cc.png
    - assets/images/board_create.png

    # Chat
    - assets/images/chat_input_send.png
    - assets/images/file_plus.png
    - assets/images/banner_deco.png
    - assets/images/file_before_download.png
    - assets/images/file_after_download.png
    - assets/images/file_send_camera.png
    - assets/images/file_send_gallery.png
    - assets/images/file_send_etc.png
    - assets/images/chatting_down.png
    - assets/images/400.png
    - assets/images/401.png


    

    # - assets/fonts/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # 폰트 개같아서 지움(디자인 회사에서 안드로이드 디폴트 폰트 써래)
  fonts:
    # - family: PingFangSC
    #   fonts:
    #     - asset: assets/fonts/PingFang SC Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/PingFang SC Regular.ttf
    #       weight: 400
    
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
    
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
